# HyprEmoji Configuration

# Keybind to open hypremoji
bind = SUPER, period, exec, hypremoji

# Window rules for HyprEmoji
windowrule = float true, match:title ^(HyprEmoji)$ 
windowrule = move 647 72, match:title ^(HyprEmoji)$
windowrule = size 611 626, match:title ^(HyprEmoji)$
