
#
# Default configuration for reddittui.
# Uncomment to configure
#

#[core]
#bypassCache = false
#logLevel = "Warn"

[filter]
#keywords = ["rice"]
subreddits = ["hyprland", "TOTK", "unixporn", "linuxmemes", "arch", "firefoxcss"]

#[client]
#timeoutSeconds = 10
#cacheTtlSeconds = 3600

#[server]
#domain = "old.reddit.com"
#type = "old"
