source = ~/.config/hypr/colors.conf

general {
	bezier = ease-in-out, 0.55, 0, 0, 1.01
	animation = fadeIn, 1, 1.8, ease-in-out
}

background {
	path = $image
	blur_passes = 2
}

label {
	text = cmd[update:1000] echo -e "<b>$(date +"%H")</b>"
	position = 0, 150
    halign = center
	valign = center
	color = $primary_container
	font_size = 200
}
label {
	text = cmd[update:1000] echo -e "<b>$(date +"%M")</b>"
	position = 0, -135
    halign = center
    valign = center
    color = $primary_container
    font_size = 200
}
input-field {
    size = 20%, 5%
    outline_thickness = 3
    inner_color = $background
	dots_text_format = 
	placeholder_text = $DESC
    outer_color = $primary_container
    fail_color=

    font_color = $primary
    fade_on_empty = true
    rounding = 15
	
    position = 0, 0
    halign = center
    valign = center
}
label {
	text = cmd[update:0] hyprctl splash
	position = 0, -335
    halign = center
    valign = center
    color = $primary
    font_size = 12
}
image{
	path = cmd[update:1] playerctl metadata mpris:artUrl
    size = 200
    rounding = 20
    border_size = 0
    position = 0, 0
}
