github.com:
    users:
        RandomMonkey99:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: RandomMonkey99
