[config]
source = "wallpaper"

[config.wallpaper]
command = "awww img {{ image }} -t wipe ; ln -f {{ image }} ~/.config/wallpaper/wallpaper.png"
set = true

[templates.vscode-raw]
input_path = './templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = './templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/config.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.eww]
input_path = '~/.config/matugen/templates/eww.scss'
output_path = '~/.config/eww/eww.scss'

[templates.hyprland]
input_path = '~/.config/matugen/templates/colors.lua'
output_path = '~/.config/hypr/modules/colors.lua'

[templates.cava]
input_path = '~/.config/matugen/templates/cava.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.mako]
input_path = '~/.config/matugen/templates/mako'
output_path = '~/.config/mako/config'
post_hook = 'killall mako && mako &'

[templates.micro]
input_path = '~/.config/matugen/templates/micro.micro'
output_path = '~/.config/micro/colorschemes/matugen.micro'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/current-theme.conf'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = '~/.config/matugen/post-hook-scripts/gtk-themes-reload.sh'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = '/home/rm99/.local/bin/pywalfox update'

[templates.fzf]
input_path = "~/.config/matugen/templates/fzf.sh"
output_path = "~/.config/fzf/colors.sh"

[templates.quickshell]
input_path = '~/.config/matugen/templates/quickshell.json'
output_path = '~/.local/state/quickshell/generated/colors.json'
