local variables = require("modules.variables")
local colors = require("modules.colors")

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprlock")
    hl.exec_cmd("restore_wall")
    hl.exec_cmd("waybar ")
    hl.exec_cmd("swayosd-server & swayosd-libinput-backend")
    hl.exec_cmd("hyprpm reload")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("kitten panel --edge=background -o background_opacity=0 -o default_pointer_shape=arrow cava")
    hl.exec_cmd("eww open splash")
end)
